// ============================================================
// FEC Analyzer — Mapping Tables (PCG → P&L / BFR / Dette Nette)
// Source: Expert-comptable TS/M&A — version 3.0-TS-Master
// ============================================================

import type { PnlMappingLine, BfrMappingLine, NetDebtMappingLine, KpiMappingLine } from "./types";

// --- Metadata ---
export const MAPPING_VERSION = "3.0-TS-Master";
export const PCG_VERSION = "PCG 2025";

/** Journaux à exclure du P&L (à-nouveaux, clôture) */
export const PNL_EXCLUDED_JOURNALS = ["AN", "RAN", "ANOUV", "OUV"];

/** Journaux de clôture (inclure les 6x/7x mais exclure le reste) */
export const CLOSURE_JOURNALS = ["CLO", "SIT", "BILAN"];

/** Comptes à exclure du P&L (affectation résultat) */
export const PNL_EXCLUDED_ACCOUNT_PREFIXES = ["12", "89"];

// ============================================================
// TABLE 1 — P&L (SIG adapté M&A)
// ============================================================

export const PNL_MAPPING: PnlMappingLine[] = [
  {
    id: "PL_010",
    label: "Ventes de marchandises",
    type: "account",
    pcg_prefix: ["707"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_012",
    label: "RRR accordés sur ventes de marchandises",
    type: "account",
    pcg_prefix: ["7097"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_020",
    label: "Production vendue — biens et services",
    type: "account",
    pcg_prefix: ["701", "702", "703", "704", "705", "706", "708"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_022",
    label: "RRR accordés sur production vendue",
    type: "account",
    pcg_prefix: ["7091", "7092", "7093", "7094", "7095", "7096", "7098"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_030",
    label: "Chiffre d'affaires net",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_010 - PL_012 + PL_020 - PL_022",
    is_key_subtotal: true,
    restatement_flag: "none",
  },
  {
    id: "PL_040",
    label: "Production stockée",
    type: "account",
    pcg_prefix: ["71"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_050",
    label: "Production immobilisée",
    type: "account",
    pcg_prefix: ["72"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "capex_proxy",
  },
  {
    id: "PL_060",
    label: "Subventions d'exploitation",
    type: "account",
    pcg_prefix: ["74"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "one_off",
  },
  {
    id: "PL_070",
    label: "Production de l'exercice",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_030 + PL_040 + PL_050",
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_080",
    label: "Achats de marchandises (y.c. droits de douane)",
    type: "account",
    pcg_prefix: ["607"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_082",
    label: "Variation de stocks de marchandises",
    type: "account",
    pcg_prefix: ["6037"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_090",
    label: "Achats de matières premières et autres approvisionnements",
    type: "account",
    pcg_prefix: ["601", "602"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_092",
    label: "Variation de stocks de matières et approvisionnements",
    type: "account",
    pcg_prefix: ["6031", "6032"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_094",
    label: "Autres variations de stocks",
    type: "account",
    pcg_prefix: ["603"],
    pcg_exclude: ["6031", "6032", "6037"],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_100",
    label: "Sous-traitance générale",
    type: "account",
    pcg_prefix: ["611"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "ic_risk",
  },
  {
    id: "PL_102",
    label: "Crédit-bail / Locations financières",
    type: "account",
    pcg_prefix: ["612"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "lease_ifrs16",
  },
  {
    id: "PL_104",
    label: "Locations et charges locatives",
    type: "account",
    pcg_prefix: ["613", "614"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "ic_risk",
  },
  {
    id: "PL_106",
    label: "Entretien, réparations, assurances",
    type: "account",
    pcg_prefix: ["615", "616"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_108",
    label: "Études, recherches, documentation",
    type: "account",
    pcg_prefix: ["617", "618"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_110",
    label: "Personnel extérieur / Intérim",
    type: "account",
    pcg_prefix: ["621"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_112",
    label: "Honoraires et commissions",
    type: "account",
    pcg_prefix: ["622"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "ic_risk",
  },
  {
    id: "PL_114",
    label: "Publicité, publications",
    type: "account",
    pcg_prefix: ["623"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_116",
    label: "Transports de biens et collectifs",
    type: "account",
    pcg_prefix: ["624"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_118",
    label: "Déplacements, missions, réceptions",
    type: "account",
    pcg_prefix: ["625"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_120",
    label: "Frais postaux et télécoms",
    type: "account",
    pcg_prefix: ["626"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_122",
    label: "Services bancaires et assimilés",
    type: "account",
    pcg_prefix: ["627"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_124",
    label: "Divers (cotisations, dons, etc.)",
    type: "account",
    pcg_prefix: ["628"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_126",
    label: "Achats non stockés (matières, fournitures, énergie)",
    type: "account",
    pcg_prefix: ["606"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_128",
    label: "Achats d'études et prestations",
    type: "account",
    pcg_prefix: ["604", "605"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_130",
    label: "RRR obtenus sur achats",
    type: "account",
    pcg_prefix: ["609", "619", "629"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_140",
    label: "Consommation de l'exercice",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_080 + PL_082 + PL_090 + PL_092 + PL_094 + PL_100 + PL_102 + PL_104 + PL_106 + PL_108 + PL_110 + PL_112 + PL_114 + PL_116 + PL_118 + PL_120 + PL_122 + PL_124 + PL_126 + PL_128 - PL_130",
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_150",
    label: "Valeur Ajoutée",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_070 - PL_140",
    is_key_subtotal: true,
    restatement_flag: "none",
  },
  {
    id: "PL_160",
    label: "Impôts, taxes et versements assimilés (hors CVAE)",
    type: "account",
    pcg_prefix: ["63"],
    pcg_exclude: ["6352"],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_162",
    label: "CVAE",
    type: "account",
    pcg_prefix: ["6352"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "cvae_reclass",
  },
  {
    id: "PL_170",
    label: "Salaires et traitements",
    type: "account",
    pcg_prefix: ["641", "642", "644"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_172",
    label: "Rémunération exploitant / gérant TNS",
    type: "account",
    pcg_prefix: ["643"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "director_comp",
  },
  {
    id: "PL_174",
    label: "Charges sociales",
    type: "account",
    pcg_prefix: ["645", "647"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_176",
    label: "Cotisations sociales personnelles de l'exploitant",
    type: "account",
    pcg_prefix: ["646"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "director_comp",
  },
  {
    id: "PL_178",
    label: "Autres charges de personnel",
    type: "account",
    pcg_prefix: ["648"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_180",
    label: "Excédent Brut d'Exploitation / EBITDA",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_150 + PL_060 - PL_160 - PL_162 - PL_170 - PL_172 - PL_174 - PL_176 - PL_178",
    is_key_subtotal: true,
    restatement_flag: "none",
  },
  {
    id: "PL_190",
    label: "Dotations aux amortissements et provisions — exploitation",
    type: "account",
    pcg_prefix: ["681"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_200",
    label: "Reprises sur amortissements et provisions — exploitation",
    type: "account",
    pcg_prefix: ["781"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_210",
    label: "Transferts de charges d'exploitation",
    type: "account",
    pcg_prefix: ["791"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_220",
    label: "Autres produits de gestion courante",
    type: "account",
    pcg_prefix: ["75"],
    pcg_exclude: ["755"],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_222",
    label: "Quotes-parts résultat sur opérations en commun (produit)",
    type: "account",
    pcg_prefix: ["755"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_230",
    label: "Autres charges de gestion courante",
    type: "account",
    pcg_prefix: ["65"],
    pcg_exclude: ["655"],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "one_off",
  },
  {
    id: "PL_232",
    label: "Quotes-parts résultat sur opérations en commun (charge)",
    type: "account",
    pcg_prefix: ["655"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_240",
    label: "Résultat d'Exploitation / EBIT",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_180 - PL_190 + PL_200 + PL_210 + PL_220 + PL_222 - PL_230 - PL_232",
    is_key_subtotal: true,
    restatement_flag: "none",
  },
  {
    id: "PL_250",
    label: "Produits financiers",
    type: "account",
    pcg_prefix: ["76"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_252",
    label: "Dotations financières",
    type: "account",
    pcg_prefix: ["686"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_254",
    label: "Reprises financières",
    type: "account",
    pcg_prefix: ["786"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_260",
    label: "Charges financières",
    type: "account",
    pcg_prefix: ["66"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_270",
    label: "Résultat Financier",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_250 + PL_254 - PL_252 - PL_260",
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_280",
    label: "Résultat Courant Avant Impôts",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_240 + PL_270",
    is_key_subtotal: true,
    restatement_flag: "none",
  },
  {
    id: "PL_290",
    label: "Produits exceptionnels",
    type: "account",
    pcg_prefix: ["77"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "one_off",
  },
  {
    id: "PL_292",
    label: "Dotations exceptionnelles",
    type: "account",
    pcg_prefix: ["687"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "one_off",
  },
  {
    id: "PL_294",
    label: "Reprises exceptionnelles",
    type: "account",
    pcg_prefix: ["787"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "one_off",
  },
  {
    id: "PL_300",
    label: "Charges exceptionnelles",
    type: "account",
    pcg_prefix: ["67"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "one_off",
  },
  {
    id: "PL_310",
    label: "Résultat Exceptionnel",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_290 + PL_294 - PL_292 - PL_300",
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_320",
    label: "Participation des salariés",
    type: "account",
    pcg_prefix: ["691"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_330",
    label: "Impôt sur les bénéfices",
    type: "account",
    pcg_prefix: ["695"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_332",
    label: "Crédits d'impôts (CIR, CICE, etc.)",
    type: "account",
    pcg_prefix: ["699"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "cir_reclass",
  },
  {
    id: "PL_340",
    label: "Résultat Net",
    type: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    sign: "formula",
    formula: "PL_280 + PL_310 - PL_320 - PL_330 + PL_332",
    is_key_subtotal: true,
    restatement_flag: "none",
  },
  {
    id: "PL_900",
    label: "[CONTRÔLE] Solde du compte 120/129",
    type: "account",
    pcg_prefix: ["120", "129"],
    pcg_exclude: [],
    sign: "credit_minus_debit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "none",
  },
  {
    id: "PL_910",
    label: "[ALERTE] Comptes d'attente P&L (471)",
    type: "account",
    pcg_prefix: ["471"],
    pcg_exclude: [],
    sign: "debit_minus_credit",
    formula: null,
    is_key_subtotal: false,
    restatement_flag: "unmapped",
  },
];

// ============================================================
// TABLE 2 — BFR (Besoin en Fonds de Roulement)
// ============================================================

export const BFR_MAPPING: BfrMappingLine[] = [
  // --- Actif circulant opérationnel ---
  {
    id: "BFR_010",
    label: "Créances clients et comptes rattachés",
    category: "operating_asset",
    pcg_prefix: ["411", "413", "416", "418"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: "DSO",
  },
  {
    id: "BFR_012",
    label: "Clients — retenues de garantie",
    category: "operating_asset",
    pcg_prefix: ["417"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: "DSO",
  },
  {
    id: "BFR_014",
    label: "Provisions pour dépréciation des créances clients",
    category: "operating_asset",
    pcg_prefix: ["491"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_020",
    label: "Stocks de matières premières et approvisionnements",
    category: "operating_asset",
    pcg_prefix: ["31", "32"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: "DIO",
  },
  {
    id: "BFR_022",
    label: "En-cours de production — biens",
    category: "operating_asset",
    pcg_prefix: ["33"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_024",
    label: "En-cours de production — services",
    category: "operating_asset",
    pcg_prefix: ["34"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_026",
    label: "Produits intermédiaires et finis",
    category: "operating_asset",
    pcg_prefix: ["35"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_028",
    label: "Stocks de marchandises",
    category: "operating_asset",
    pcg_prefix: ["37"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: "DIO",
  },
  {
    id: "BFR_030",
    label: "Provisions pour dépréciation des stocks",
    category: "operating_asset",
    pcg_prefix: ["391", "392", "393", "394", "395", "396", "397"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_040",
    label: "Avances et acomptes versés sur commandes",
    category: "operating_asset",
    pcg_prefix: ["4091"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_050",
    label: "Personnel — avances et acomptes",
    category: "operating_asset",
    pcg_prefix: ["425"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_060",
    label: "Charges constatées d'avance",
    category: "operating_asset",
    pcg_prefix: ["486"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_070",
    label: "Autres créances d'exploitation",
    category: "operating_asset",
    pcg_prefix: ["4097", "4098", "4387", "4486", "4487"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "positive",
    formula: null,
    linked_ratio: null,
  },
  // --- Passif circulant opérationnel ---
  {
    id: "BFR_110",
    label: "Dettes fournisseurs et comptes rattachés",
    category: "operating_liability",
    pcg_prefix: ["401", "403", "408"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: "DPO",
  },
  {
    id: "BFR_112",
    label: "Avances et acomptes reçus sur commandes",
    category: "operating_liability",
    pcg_prefix: ["419"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_120",
    label: "Dettes sociales",
    category: "operating_liability",
    pcg_prefix: ["42", "43"],
    pcg_exclude: ["424", "425", "4284"],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_122",
    label: "Dettes sur participation et intéressement",
    category: "operating_liability",
    pcg_prefix: ["424", "4284"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_130",
    label: "Dettes fiscales (hors TVA, hors IS)",
    category: "operating_liability",
    pcg_prefix: ["44"],
    pcg_exclude: ["444", "445"],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_140",
    label: "Produits constatés d'avance",
    category: "operating_liability",
    pcg_prefix: ["487"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_150",
    label: "Autres dettes d'exploitation",
    category: "operating_liability",
    pcg_prefix: ["4198", "464", "467", "4686", "4687"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "negative",
    formula: null,
    linked_ratio: null,
  },
  // --- Sous-totaux ---
  {
    id: "BFR_200",
    label: "Actif circulant opérationnel",
    category: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    balance: "formula",
    bfr_sign: "formula",
    formula:
      "BFR_010 + BFR_012 - BFR_014 + BFR_020 + BFR_022 + BFR_024 + BFR_026 + BFR_028 - BFR_030 + BFR_040 + BFR_050 + BFR_060 + BFR_070",
    linked_ratio: null,
  },
  {
    id: "BFR_210",
    label: "Passif circulant opérationnel",
    category: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    balance: "formula",
    bfr_sign: "formula",
    formula: "BFR_110 + BFR_112 + BFR_120 + BFR_122 + BFR_130 + BFR_140 + BFR_150",
    linked_ratio: null,
  },
  {
    id: "BFR_220",
    label: "BFR Opérationnel",
    category: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    balance: "formula",
    bfr_sign: "formula",
    formula: "BFR_200 - BFR_210",
    linked_ratio: null,
  },
  // --- Hors exploitation (pour réconciliation) ---
  {
    id: "BFR_310",
    label: "TVA déductible",
    category: "non_operating",
    pcg_prefix: ["4456"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_312",
    label: "TVA collectée / TVA à décaisser",
    category: "non_operating",
    pcg_prefix: ["4457", "4455"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_314",
    label: "Crédit de TVA",
    category: "non_operating",
    pcg_prefix: ["44567"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_320",
    label: "IS à payer",
    category: "non_operating",
    pcg_prefix: ["444"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_330",
    label: "Comptes courants d'associés",
    category: "non_operating",
    pcg_prefix: ["455"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_332",
    label: "Dividendes à payer",
    category: "non_operating",
    pcg_prefix: ["457"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_340",
    label: "Comptes inter-sociétés",
    category: "non_operating",
    pcg_prefix: ["451"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_350",
    label: "Fournisseurs d'immobilisations",
    category: "non_operating",
    pcg_prefix: ["404"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  // --- Trésorerie ---
  {
    id: "BFR_400",
    label: "Trésorerie active",
    category: "cash",
    pcg_prefix: ["512", "514", "517", "53"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_410",
    label: "Concours bancaires courants",
    category: "cash",
    pcg_prefix: ["519"],
    pcg_exclude: [],
    balance: "credit_minus_debit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
  {
    id: "BFR_420",
    label: "Trésorerie nette",
    category: "subtotal",
    pcg_prefix: [],
    pcg_exclude: [],
    balance: "formula",
    bfr_sign: "info",
    formula: "BFR_400 - BFR_410",
    linked_ratio: null,
  },
  {
    id: "BFR_910",
    label: "[ALERTE] Comptes d'attente Bilan (471)",
    category: "non_operating",
    pcg_prefix: ["471"],
    pcg_exclude: [],
    balance: "debit_minus_credit",
    bfr_sign: "info",
    formula: null,
    linked_ratio: null,
  },
];

// ============================================================
// TABLE 3 — Dette Nette
// ============================================================

export const NET_DEBT_MAPPING: NetDebtMappingLine[] = [
  {
    id: "DN_010",
    label: "Emprunts auprès des établissements de crédit",
    category: "bank_debt",
    pcg_prefix: ["161"],
    balance: "credit_minus_debit",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_020",
    label: "Emprunts obligataires",
    category: "other_financial_debt",
    pcg_prefix: ["160", "163"],
    balance: "credit_minus_debit",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_030",
    label: "Autres emprunts et dettes financières",
    category: "other_financial_debt",
    pcg_prefix: ["164", "165", "167", "168"],
    balance: "credit_minus_debit",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_040",
    label: "Intérêts courus sur emprunts",
    category: "other_financial_debt",
    pcg_prefix: ["1688", "5181"],
    balance: "credit_minus_debit",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_050",
    label: "Concours bancaires courants",
    category: "bank_debt",
    pcg_prefix: ["519"],
    balance: "credit_minus_debit",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_060",
    label: "Primes de remboursement des emprunts",
    category: "other_financial_debt",
    pcg_prefix: ["169"],
    balance: "debit_minus_credit",
    sign_in_net_debt: "negative",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_070",
    label: "Comptes courants d'associés (part dette)",
    category: "shareholder",
    pcg_prefix: ["455"],
    balance: "credit_minus_debit",
    sign_in_net_debt: "manual",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_080",
    label: "Dividendes à payer",
    category: "shareholder",
    pcg_prefix: ["457"],
    balance: "credit_minus_debit",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_100",
    label: "[MANUEL] Encours crédit-bail retraité IFRS 16",
    category: "manual_adjustment",
    pcg_prefix: [],
    balance: "formula",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: true,
  },
  {
    id: "DN_110",
    label: "[MANUEL] Affacturage hors bilan",
    category: "manual_adjustment",
    pcg_prefix: [],
    balance: "formula",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: true,
  },
  {
    id: "DN_120",
    label: "[MANUEL] PGE résiduel (si non dans 161)",
    category: "manual_adjustment",
    pcg_prefix: [],
    balance: "formula",
    sign_in_net_debt: "positive",
    formula: null,
    is_manual: true,
  },
  {
    id: "DN_200",
    label: "Total dette financière brute (hors CCA)",
    category: "subtotal",
    pcg_prefix: [],
    balance: "formula",
    sign_in_net_debt: "formula",
    formula: "DN_010 + DN_020 + DN_030 + DN_040 + DN_050 - DN_060 + DN_080 + DN_100 + DN_110 + DN_120",
    is_manual: false,
  },
  {
    id: "DN_300",
    label: "Trésorerie — Banques",
    category: "cash",
    pcg_prefix: ["512", "514", "517"],
    balance: "debit_minus_credit",
    sign_in_net_debt: "negative",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_310",
    label: "Trésorerie — Caisse",
    category: "cash",
    pcg_prefix: ["53"],
    balance: "debit_minus_credit",
    sign_in_net_debt: "negative",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_320",
    label: "VMP (si liquidités)",
    category: "cash",
    pcg_prefix: ["50"],
    balance: "debit_minus_credit",
    sign_in_net_debt: "negative",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_330",
    label: "Dépôts et cautionnements versés",
    category: "manual_adjustment",
    pcg_prefix: ["275"],
    balance: "debit_minus_credit",
    sign_in_net_debt: "manual",
    formula: null,
    is_manual: false,
  },
  {
    id: "DN_400",
    label: "Trésorerie totale",
    category: "subtotal",
    pcg_prefix: [],
    balance: "formula",
    sign_in_net_debt: "formula",
    formula: "DN_300 + DN_310 + DN_320",
    is_manual: false,
  },
  {
    id: "DN_500",
    label: "Dette nette (hors CCA)",
    category: "subtotal",
    pcg_prefix: [],
    balance: "formula",
    sign_in_net_debt: "formula",
    formula: "DN_200 - DN_400",
    is_manual: false,
  },
  {
    id: "DN_510",
    label: "Dette nette (incluant CCA)",
    category: "subtotal",
    pcg_prefix: [],
    balance: "formula",
    sign_in_net_debt: "formula",
    formula: "DN_200 + DN_070 - DN_400",
    is_manual: false,
  },
];

// ============================================================
// TABLE 4 — KPIs / Ratios (filtrable par secteur)
// ============================================================

export const KPI_MAPPING: KpiMappingLine[] = [
  // --- Profitabilité ---
  {
    id: "KPI_010",
    name: "Marge commerciale stricte (Négoce)",
    category: "profitability",
    formula: "(PL_010 - PL_012 - PL_080 - PL_082) / (PL_010 - PL_012) * 100",
    unit: "percent",
    sector_relevance: ["distribution", "industry"],
    benchmark: "25-50%",
    alert_below: 20,
    alert_above: null,
  },
  {
    id: "KPI_020",
    name: "Taux de valeur ajoutée",
    category: "profitability",
    formula: "PL_150 / PL_030 * 100",
    unit: "percent",
    sector_relevance: ["all"],
    benchmark: "25-60%",
    alert_below: 20,
    alert_above: null,
  },
  {
    id: "KPI_030",
    name: "Taux de sous-traitance",
    category: "profitability",
    formula: "PL_100 / PL_030 * 100",
    unit: "percent",
    sector_relevance: ["btp", "esn", "industry"],
    benchmark: "5-25%",
    alert_below: null,
    alert_above: 30,
  },
  {
    id: "KPI_040",
    name: "Taux d'intérim",
    category: "profitability",
    formula: "PL_110 / PL_030 * 100",
    unit: "percent",
    sector_relevance: ["btp", "industry"],
    benchmark: "2-10%",
    alert_below: null,
    alert_above: 15,
  },
  {
    id: "KPI_050",
    name: "Poids de la masse salariale",
    category: "profitability",
    formula: "(PL_170 + PL_172 + PL_174 + PL_176 + PL_178) / PL_030 * 100",
    unit: "percent",
    sector_relevance: ["all"],
    benchmark: "30-60%",
    alert_below: null,
    alert_above: 70,
  },
  {
    id: "KPI_060",
    name: "Marge EBITDA",
    category: "profitability",
    formula: "PL_180 / PL_030 * 100",
    unit: "percent",
    sector_relevance: ["all"],
    benchmark: "8-20%",
    alert_below: 5,
    alert_above: null,
  },
  {
    id: "KPI_070",
    name: "Marge EBIT",
    category: "profitability",
    formula: "PL_240 / PL_030 * 100",
    unit: "percent",
    sector_relevance: ["all"],
    benchmark: "5-15%",
    alert_below: 3,
    alert_above: null,
  },
  {
    id: "KPI_080",
    name: "Marge nette",
    category: "profitability",
    formula: "PL_340 / PL_030 * 100",
    unit: "percent",
    sector_relevance: ["all"],
    benchmark: "3-10%",
    alert_below: 0,
    alert_above: null,
  },
  // --- Activité / BFR ---
  {
    id: "KPI_090",
    name: "DSO (Days Sales Outstanding)",
    category: "activity",
    formula: "BFR_010 / (PL_030 / 360)",
    unit: "days",
    sector_relevance: ["all"],
    benchmark: "45-60",
    alert_below: null,
    alert_above: 75,
  },
  {
    id: "KPI_100",
    name: "DPO (Days Payable Outstanding)",
    category: "activity",
    formula: "BFR_110 / (PL_140 / 360)",
    unit: "days",
    sector_relevance: ["all"],
    benchmark: "45-60",
    alert_below: 30,
    alert_above: 90,
  },
  {
    id: "KPI_110",
    name: "DIO (Days Inventory Outstanding)",
    category: "activity",
    formula: "(BFR_020 + BFR_022 + BFR_024 + BFR_026 + BFR_028) / (PL_140 / 360)",
    unit: "days",
    sector_relevance: ["industry", "distribution", "btp"],
    benchmark: "30-60",
    alert_below: null,
    alert_above: 90,
  },
  {
    id: "KPI_120",
    name: "BFR en jours de CA",
    category: "activity",
    formula: "BFR_220 / (PL_030 / 360)",
    unit: "days",
    sector_relevance: ["all"],
    benchmark: "30-60",
    alert_below: null,
    alert_above: 90,
  },
  {
    id: "KPI_130",
    name: "Taux de capitalisation R&D",
    category: "profitability",
    formula: "PL_050 / (PL_170 + PL_172 + PL_174 + PL_176 + PL_178) * 100",
    unit: "percent",
    sector_relevance: ["software"],
    benchmark: "0-15%",
    alert_below: null,
    alert_above: 20,
  },
  {
    id: "KPI_140",
    name: "Poids des revenus différés",
    category: "activity",
    formula: "BFR_140 / (PL_030 / 12)",
    unit: "multiple",
    sector_relevance: ["software", "esn"],
    benchmark: "2-6 mois",
    alert_below: 1,
    alert_above: null,
  },
  {
    id: "KPI_150",
    name: "Poids des en-cours",
    category: "activity",
    formula: "(BFR_022 + BFR_024) / (PL_030 / 360)",
    unit: "days",
    sector_relevance: ["btp", "industry"],
    benchmark: "10-30",
    alert_below: null,
    alert_above: 45,
  },
  {
    id: "KPI_160",
    name: "Taux de couverture par les acomptes",
    category: "coverage",
    formula: "BFR_112 / BFR_010 * 100",
    unit: "percent",
    sector_relevance: ["btp", "industry"],
    benchmark: "10-30%",
    alert_below: 5,
    alert_above: null,
  },
  {
    id: "KPI_170",
    name: "Poids des retenues de garantie",
    category: "activity",
    formula: "BFR_012 / BFR_010 * 100",
    unit: "percent",
    sector_relevance: ["btp"],
    benchmark: "0-10%",
    alert_below: null,
    alert_above: 15,
  },
  {
    id: "KPI_180",
    name: "Productivité salariale",
    category: "profitability",
    formula: "PL_030 / (PL_170 + PL_172 + PL_174 + PL_176 + PL_178)",
    unit: "multiple",
    sector_relevance: ["esn", "software", "all"],
    benchmark: "1.8x - 2.5x",
    alert_below: 1.5,
    alert_above: null,
  },
  {
    id: "KPI_190",
    name: "EBITDA Cash Conversion Proxy",
    category: "coverage",
    formula: "(PL_180 - PL_050) / PL_180 * 100",
    unit: "percent",
    sector_relevance: ["all"],
    benchmark: "80-100%",
    alert_below: 70,
    alert_above: null,
  },
];
